language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database byob_test;' -U postgres
notifications:
  email: false
deploy:
  api_key:
    secure: GQfeAY/4EooCJGRYlMnB/2Og9yriab/x2odT4gWTVc6iQwTdkZOSApJn8+naQyk05N6cg6YGcvP+iT5TbgCRPbzQvOzmUV/d1vMNHNTnT5fOwvPpnR04NHtbyJluqY+4oM9GG+oIAs0opo4YjA0f/oghR+7Ele3GDtdSJWIT8aGKn4+DJiaVpYa6PtecNYRMjweJxVPbp1OZ84iA4iYzTANL7A7sAvKwEvSMTWh1IIMb4jTxNLKV1QmFX9vNbm1QZFv1Nq9Azm1W7TzX5YzC0lCApcSuv+RYk8V74CbsWCFXvNFFdWjv03A2LCQGdDfSbvDmTbVDIv7DkzWmpoLtZm9dahNAWlskcTpguyux2v5ExRMC0wsFHHVlCtRW5iwWEJuzsRAXMbaCD4Q2Pyhjm4MfnqL2JwhSWyrwDCfg3bqyBXzhGUy2xu6xJJ+ahGG6sw0qXEKNO6L5/kYgBENT5JCIu404/tJqz0bCUDmy6NYEFCrbmrGcOlFK2Ja/Ma9C96NBVTFNXvGnvYq/nW0jJMc6vn8P6nRcRoBI/wpzyi0iUBVZMijElETq6Gm9X7zLQCbvn0rqp0bQCWg1ap1gwsWHwB4wKF7G1li5qZJ3FGsuDmDQqHBTEG7rk6U+RgkHf/Hchh5hMDdz0POLg4RfUNfOHjV047U2Frg57lyioSM=
  app: byob-1711
  skip_cleanup: true
  on:
    all_branches: true
